---

checks:
  argument-count:
    enabled: false
  method-complexity:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-60
    config:
      file: .circleci/linter_configs/.rubocop.yml

  reek:
    enabled: true
